version: '3'
services:
  postgres:
    container_name: postgres-chat-db
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-chat}
      - POSTGRES_PORT=${POSTGRES_PORT:-5433}
      - POSTGRES_INITDB_ARGS="--max_connections=1000"
    ports:
      - "${POSTGRES_PORT:-5433}:${POSTGRES_PORT:-5433}"
    command: ["postgres", "-p", "${POSTGRES_PORT:-5433}", "-c", "max_connections=1000", "-c", "shared_buffers=512MB", "-N", "1000"]
    networks:
      - local_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongodb-chat-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-chat}
    networks:
      - local_network
  redis:
    image: redis:alpine
    container_name: redis-chat-db
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - local_network
  web:
    container_name: web-app-chat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - local_network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - local_network
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - local_network

networks:
  local_network:
    driver: bridge