version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis-chat-db
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - local_network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - local_network
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
    networks:
      - local_network
  mongodb:
    image: mongo
    container_name: mongodb-chat-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-chat}
    networks:
      - local_network
networks:
  local_network:
    driver: bridge
