version: '3'
services:
  postgres:
    container_name: postgres-chat-db
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-chat}
    ports:
      - "5433:5433"
    networks:
      - local_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis-chat-db
    command: redis-server --requirepass ${REDIS_PASSWORD:-change}
    ports:
      - "6379:6379"
    networks:
      - local_network
  web:
    container_name: web-app-chat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - local_network
networks:
  local_network:
    driver: bridge