"""lights_updated_at

Revision ID: 22d3431a6d8d
Revises: c84388d0e634
Create Date: 2023-12-27 15:28:26.463328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d3431a6d8d'
down_revision: Union[str, None] = 'c84388d0e634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lights', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lights', 'updated_at')
    # ### end Alembic commands ###
