"""messages_reply_id_is_edited

Revision ID: c0a079e2cea9
Revises: 22d3431a6d8d
Create Date: 2023-12-27 17:07:45.578265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a079e2cea9'
down_revision: Union[str, None] = '22d3431a6d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'reply_id')
    # ### end Alembic commands ###
