"""lights_acked

Revision ID: c84388d0e634
Revises: c0f032dd2409
Create Date: 2023-12-27 09:56:45.056127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84388d0e634'
down_revision: Union[str, None] = 'c0f032dd2409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lights', sa.Column('acked', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'lights', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lights', type_='unique')
    op.drop_column('lights', 'acked')
    # ### end Alembic commands ###
